### ISSUE TITLE
Неточности в документации

### ISSUE THREAD

**Issue by glebe** [freematiq/payin-api#13]
- Метод оплаты 22 (карты high risk) не работает
- successUrl колбек приходит не методом post, как указано, а GET
- не указана минимальная сумма платежа в 2р, что вызывает неочевидную проблему отказа при тестировании оплаты

**Comment by Shaamin** [comment]
- Была поправлена верстка и был убран метод оплаты 22 (карты high risk)
- Не нашел в документации, где бы так было написано. Просьба привести место из документации
- Вопрос по ОР: как известно, минимальная сумма определяется на шлюзе и провайдере, но не на сервисе. От сюда вытекает кейс: минимальная сумма по сервисам зависит от индивидуальных настроек пользователя в ЛК. Значит, минимальная сумма по сервису плавающая величина и может быть изменена для разных пользователей в разное время. Собственно вопрос: какой исходя из ситуации вы ожидаете результат?

**Comment by freematiq** [comment]
Неточности устранены? Закрываю тикет. Откройте новый если найдёте что-то.
